name: AI Powered Sales Prediction CD to AWS Lambda

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 

      
      - name: Build and Push Node.js Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sales-node-app
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./backend-node
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          # ল্যাম্বডা আপডেট (যদি ফাংশন তৈরি করা থাকে)
          aws lambda update-function-code --function-name NodeSalesFunction --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest || echo "Lambda function not found"

      
      - name: Build and Push Python Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sales-python-ml
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./backend-python
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          # ল্যাম্বডা আপডেট
          aws lambda update-function-code --function-name PythonMLFunction --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest || echo "Lambda function not found"